#%includefile option("helix")
[[language]]
name = "rust"

#%if chip.xtensa
[language-server.rust-analyzer]
environment.RUSTUP_TOOLCHAIN = "stable"

#%endif
[language-server.rust-analyzer.config]
cargo.allTargets = false
#REPLACE riscv32imac-unknown-none-elf rust_target
cargo.target = "riscv32imac-unknown-none-elf"
#%if chip.xtensa
#REPLACE esp rust_toolchain
cargo.extraEnv.RUSTUP_TOOLCHAIN = "esp"
#%endif
