# Keep compilation settings in this file and user/runtime settings in `esp-config.toml`.
include = ["esp-config.toml"]

[target.{{ rust_target }}]
#%if option("probe-rs")
runner = "probe-rs run --chip={{ chip }} --preverify --always-print-stacktrace --no-location"
#%else if option("defmt")
#+runner = "espflash flash --monitor --chip {{ chip }} --log-format defmt"
#%else
#+runner = "espflash flash --monitor --chip {{ chip }}"
#%endif

[build]
rustflags = [
#%if is_xtensa
  "-C", "link-arg=-nostartfiles",
#%else if is_riscv
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
#%endif
#%if option("stack-smashing-protection")
  "-Z", "stack-protector=all",
#%endif
]

target = "{{ rust_target }}"

[unstable]
#%if option("alloc")
build-std = ["alloc", "core"]
#%else
#+build-std = ["core"]
#%endif
